title: Chinmaya Kumar
position: Ph.D. Student
affiliation: Harris School of Public Policy, University of Chicago
email: <a href="mailto:chinmayak@uchicago.edu">chinmayak@uchicago.edu</a>
keywords: Development economics 
#google_scholar: https://scholar.google.com/
github_link: https://github.com/chinmayak
twitter: https://twitter.com/chinmayak
avatar: ./assets/img/chin.jpg
#google_analytics: UA-111540567-4
#favicon: ./assets/img/favicon.png
#favicon_dark: ./assets/img/favicon-dark.png
description: Chinmaya Kumar's homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
