title: Chinmaya Kumar
position: Ph.D. Student
affiliation: Harris School of Public Policy, University of Chicago
email: chinmayak (at) uchicago.edu
keywords: Development economics 
#google_scholar: https://scholar.google.com/
github_link: https://github.com/chinmayak
#linkedin: https://www.linkedin.com/
avatar: ./assets/img/chin.jpg
#google_analytics: UA-111540567-4
#favicon: ./assets/img/favicon.png
#favicon_dark: ./assets/img/favicon-dark.png
description: Chinmaya Kumar's homepage.
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
